name: Reddit Sentiment Scraper

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install libraries
      run: pip install -r requirements.txt

    - name: Run scraper
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
      run: python scrapper_job.py

    - name: Commit CSV
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add sentiment.csv
        git commit -m "update sentiment data" || echo "no changes"
        git push